### Create new Expense
POST http://localhost:8080/api/expenses
Content-Type: application/json

{
  "id": 4,
  "description": "Buy a car",
  "category": "Food",
  "dateCreation": "2025-01-01",
  "cost": 2500.00
}

### Create an Expense with invalid cost value
POST http://localhost:8080/api/expenses
Content-Type: application/json

{
  "id": 4,
  "description": "Pay internet",
  "category": "Food",
  "dateCreation": "2025-01-01",
  "cost": "twenty"
}


### Create a Expense with only blank spaces in description
POST http://localhost:8080/api/expenses
Content-Type: application/json

{
  "id": 8,
  "description": "  ",
  "category": "Food",
  "dateCreation": "2025-01-01",
  "cost": 1.0
}

### Update Expense with id: 4
PUT http://localhost:8080/api/expenses/4
Content-Type:application/json

{
  "id": 4,
  "description": "Pay tax",
  "category": "Food",
  "dateCreation": "2025-01-01",
  "cost": 55.00
}

### Get Expense with id: 1
GET http://localhost:8080/api/expenses/1

### Get Expense with id 99 that doesn't exist
GET http://localhost:8080/api/expenses/99


### Get all expenses
GET http://localhost:8080/api/expenses


### Delete a Expense with id 4
DELETE http://localhost:8080/api/expenses/4