### Create new Expense
POST http://localhost:8080/api/v1/expenses
Content-Type: application/json

{  "description": "Buy a motorbike",
  "category": "Other",
  "dateCreation": "2025-01-04",
  "cost": 2500.00
}

### Create an Expense with invalid cost value
POST http://localhost:8080/api/v1/expenses
Content-Type: application/json

{  "description": "Pay internet",
  "category": "Food",
  "dateCreation": "2025-01-01",
  "cost": "twenty"
}


### Create a Expense with only blank spaces in description
POST http://localhost:8080/api/v1/expenses
Content-Type: application/json

{

  "description": "  ",
  "category": "Food",
  "dateCreation": "2025-01-01",
  "cost": 1.0
}

### Update Expense with id: 4
PUT http://localhost:8080/api/v1/expenses/4
Content-Type:application/json

{
  "description": "Pay tax",
  "category": "Food",
  "dateCreation": "2025-01-01",
  "cost": 55.00
}

### Get Expense with id: 1
GET http://localhost:8080/api/v1/expenses/1

### Get Expense with id 99 that doesn't exist
GET http://localhost:8080/api/v1/expenses/99


### Get all expenses
GET http://localhost:8080/api/v1/expenses

### Delete a Expense with id 4
DELETE http://localhost:8080/api/v1/expenses/4


### Filter by category
GET http://localhost:8080/api/v1/expenses/category/food

### Filter by past week
GET http://localhost:8080/api/v1/expenses/pastweek

### Filter by past month
GET http://localhost:8080/api/v1/expenses/lastmonth

### Filter by last 3 months
GET http://localhost:8080/api/v1/expenses/3months

### Filter by last 6 months
GET http://localhost:8080/api/v1/expenses/months/6

### Filter by dates
GET http://localhost:8080/api/v1/expenses/date
Content-Type: application/json

{
  "startDate": "2024-12-01",
  "finishDate": "2025-01-05"
}

### Filter by cost minor or equal to 10
GET http://localhost:8080/api/v1/expenses/cost/10.0


## Categories


### Get all categories
GET http://localhost:8080/api/v1/category

### Get category with id: 3
GET http://localhost:8080/api/v1/category/3

### Create a new Category
POST http://localhost:8080/api/v1/category
Content-Type: application/json

{
  "category": "New Category"
}

### Update category with id: 7
PUT http://localhost:8080/api/v1/category/7
Content-Type: application/json

{
  "id": 8,
  "category": "Updated category"
}

### Find category
GET http://localhost:8080/api/v1/category/name/groceries


### Delete category with id 7
DELETE http://localhost:8080/api/v1/category/7

