CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    rol VARCHAR(50)  NOT NULL CHECK ( rol IN ('admin', 'client'))
);

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO categories (category)
 SELECT 'Groceries' WHERE NOT EXISTS (SELECT category FROM categories WHERE category='Groceries')  UNION ALL
 SELECT 'Leisure' WHERE NOT EXISTS (SELECT category FROM categories WHERE category='Leisure')  UNION ALL
 SELECT 'Electronics' WHERE NOT EXISTS (SELECT category FROM categories WHERE category='Electronics')  UNION ALL
 SELECT 'Utilities' WHERE NOT EXISTS (SELECT category FROM categories WHERE category='Utilities')  UNION ALL
 SELECT 'Clothing' WHERE NOT EXISTS (SELECT category FROM categories WHERE category='Clothing')  UNION ALL
 SELECT 'Health' WHERE NOT EXISTS (SELECT category FROM categories WHERE category='Health')  UNION ALL
 SELECT 'Others' WHERE NOT EXISTS (SELECT category FROM categories WHERE category='Others');



CREATE TABLE IF NOT EXISTS expenses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    category_fk INTEGER NOT NULL
        CONSTRAINT expense_category_id_fk
            REFERENCES categories,
    date_creation Date NOT NULL,
    cost DOUBLE PRECISION NOT NULL,
    user_fk INTEGER NOT NULL
        CONSTRAINT expenses_users_id_fk REFERENCES users
);